spring.security.oauth2.client.registration.google.client-id=psq2ivp5pom3m1k4orehgucusqs90a2l.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile

spring.main.allow-bean-definition-overriding=true