<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>br.com.bizuinfo</groupId>
        <artifactId>bizuinfo-erp</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>bizuinfo-venda</artifactId>
    <packaging>jar</packaging>
    <description>Vendas, pagamentos, recibo em PDF e sugestão de compra.</description>

    <dependencies>
        <dependency>
            <groupId>br.com.bizuinfo</groupId>
            <artifactId>bizuinfo-core</artifactId>
        </dependency>
        <dependency>
            <groupId>br.com.bizuinfo</groupId>
            <artifactId>bizuinfo-auditoria</artifactId>
        </dependency>
        <dependency>
            <groupId>br.com.bizuinfo</groupId>
            <artifactId>bizuinfo-usuario</artifactId>
        </dependency>
        <dependency>
            <groupId>br.com.bizuinfo</groupId>
            <artifactId>bizuinfo-produto</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.librepdf</groupId>
            <artifactId>openpdf</artifactId>
        </dependency>
    </dependencies>

</project>
